package com.mi.config;

/* compiled from: FeatureConstant */
interface c {
    public static final String rA = "s_m_l";
    public static final String rB = "s_f_s_c";
    public static final String rC = "s_e_l";
    public static final String rD = "h_d_v";
    public static final String rE = "a_l_l_l";
    public static final String rF = "a_l_h_l";
    public static final String rG = "s_s_v";
    public static final String rH = "s_s_s";
    public static final String rI = "s_u_w";
    public static final String rJ = "i_l_m_d";
    public static final String rK = "s_b_b";
    public static final String rL = "s_c_w_b";
    public static final String rM = "s_c_w_m";
    public static final String rN = "c_0x00_s_l_s";
    public static final String rO = "c_0x01_p_g_a_v";
    public static final String rP = "c_0x02_p_c_r_v";
    public static final String rQ = "c_0x03";
    public static final String rR = "c_0x04_i_l_h_d";
    public static final String rS = "c_0x05";
    public static final String rT = "c_0x06";
    public static final String rU = "c_0x07";
    public static final String rV = "c_0x08";
    public static final String rW = "c_0x09";
    public static final String rX = "c_0x0a";
    public static final String rY = "c_0x0b";
    public static final String rZ = "c_0x0c";
    public static final String rf = "s_a";
    public static final String rg = "c_t_r";
    public static final String rh = "s_i_a";
    public static final String ri = "s_z_m";
    public static final String rj = "a_e_d";
    public static final String rk = "s_m_f";
    public static final String rl = "s_p_l_b";
    public static final String rm = "s_p_l_f";
    public static final String rn = "s_f_a";
    public static final String ro = "s_p_a";
    public static final String rp = "s_v_b";
    public static final String rq = "s_o_a_w";
    public static final String rr = "s_f_s";
    public static final String rs = "s_m_c_t_f";
    public static final String rt = "s_a_3";
    public static final String ru = "s_b_m";
    public static final String rv = "s_a_u";
    public static final String rw = "s_f_9";
    public static final String rx = "s_v_f_m";
    public static final String ry = "s_f_z_i";
    public static final String rz = "s_s_n";
}
